### ISSUE TITLE
Tried out vagrant build and ran into /register 500

### ISSUE THREAD

**Issue by stevenvandervalk** [crestify/crestify#23] opened 2017-04-27 04:27 UTC
Not sure if I missed a step or what but just FYI. Looks like a great project and would love to try it out.
```
Failed to load resource: the server responded with a status of 500 (INTERNAL SERVER ERROR)
```

**Comment by dhamaniasad** [comment] 2017-04-27 09:20
Do you run into this error on only the register route or on other routes
too?

**Comment by cgrinds** [comment] 2017-04-27 11:59
I ran into the same issue - happened on register. I didn't try any other pages besides landing and register.

**Comment by dhamaniasad** [comment] 2017-04-27 13:17
Identified the issue, fix coming soon.

**Comment by dhamaniasad** [comment] 2017-04-27 13:38
This happened due to an issue related to Flask-Login. See #14. #24 closes this. 
This is how you can fix the issue now:
1. `git pull` crestify
2. Run `fab update`. This will update Crestify inside Vagrant and install the updated dependencies. (This wasn't being done with `fab update` before which is why you need to pull first)
3. There seems to be an issue with Supervisor, the earlier running Python processes seem to stick around after restarting, so you might need to `vagrant halt && vagrant up` in order to have the updated code start working.

Sorry for the inconvenience and thank you for waiting :).

**Comment by cgrinds** [comment] 2017-04-27 15:02
Did you try in a new vagrant box? I'm still unable to register.

I had already removed crestify so I repulled and started over.
`/var/log/crestify/wsgi-1.error.log` contains

`ProgrammingError: (ProgrammingError) relation "User" does not exist
LINE 2: FROM "User" 
             ^
 'SELECT "User".id AS "User_id", "User".email AS "User_email", "User".password AS "User_password", "User".first_name AS "User_first_name", "User".last_name AS "User_last_name", "User".active AS "User_active", "User".confirmed_at AS "User_confirmed_at", "User".bookmarks_per_page AS "User_bookmarks_per_page", "User".api_key AS "User_api_key" \nFROM "User" \nWHERE "User".email ILIKE %(email_1)s \n LIMIT %(param_1)s' {'email_1': u'bob@bob.com', 'param_1': 1}`

**Comment by dhamaniasad** [comment] 2017-04-27 15:12
I'll try in a new Vagrant box soon and keep this issue updated. Reopening.

**Comment by dhamaniasad** [comment] 2017-04-27 15:23
@cgrinds Can you trying SSHing into the Vagrant box, and as the user crestify, activate `/home/crestify/crestifyenv/` and run `honcho run python main.py db upgrade` and tell me if that solves the issue? The Fabric script seems to have that step missing.

**Comment by cgrinds** [comment] 2017-04-27 15:46
Those steps create the DB, but Register still fails. The page loads, submit works, but it only refreshes the page. I'll wait until you've got things squared away in a new box. Thanks.

**Comment by stevenvandervalk** [comment] 2017-05-02 06:12
Unfortunately, same here. Tried both new box and env'ed `db upgrade`.  cheers

**Comment by Hans-Maulwurf** [comment] 2017-08-21 07:28
Same issue here. Did someone manage to solve this? I would love to use crestify :/

**Comment by dhamaniasad** [comment] 2017-08-21 14:50
Sorry about this. I've been unable to manage time between running my startup and resolving these issues. I'll try to find some time and clear out the issues ASAP, but if someone else wants to take a stab at it in the meantime, you have my full support and can ping me anytime (dhamaniasad@gmail.com).

**Comment by Hans-Maulwurf** [comment] 2017-09-26 06:03
any news or updates here?

**Comment by satyanash** [comment] 2017-11-24 11:50
The user is created. You should be able to login. Verification emails are not sent.

**Comment by dhamaniasad** [comment] 2017-12-02 15:29
This has been fixed now. It was due to `Flask-Security` trying to send a registration email without having proper SMTP credentials. So sorry about the long wait guys. Do check it out now and let me know if you run into any issues.

**Closed by dhamaniasad** 2017-12-02 15:29 UTC
